routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MessageController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/
Route::post('/message/{message}', [MessageController::class, 'restoreMessage'])->name('message.restore');

Route::resource('message', MessageController::class)->except(['update', 'show', 'create']);

Route::get('/', function () {
    return redirect("/message");
});

Route::fallback(function(){
    return redirect()->route('message.index');
});

app/Models/Message.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;


class Message extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $fillable = ['message'];
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/MessageController.php
<?php

namespace App\Http\Controllers;

use App\Models\Message;
use Illuminate\Http\Request;

class MessageController extends Controller
{
    public function index()
    {
        return view('message.index', [
            'messages' => Message::latest()->get(), 
            'trashed' => Message::withTrashed()->latest('deleted_at')->where('deleted_at', '!=', 'null')->get()]);
    }

    public function restoreMessage($id)
    {
        Message::withTrashed()->find($id)->restore();
        return redirect()->route('message.index');
    }

    public function store(Request $request)
    {
        $data = $request->validate([
            'message' => 'required'
        ]);
        Message::create($data);
        return redirect()->route('message.index');
    }

    public function destroy(Message $message)
    {
        $message->delete();
        return redirect()->route('message.index');
    }
}

resources/views/message/create.blade.php
<h1 class="text-center text-4xl mb-2 font-bold">Erstellen</h1>
<form method="post" action="{{ route('message.store') }}">
    @csrf
    <label class="relative bg-white z-1 border-4 border-black p-2 top-6 -left-2" for="message">Neue Nachricht</label>
    <textarea name="message" id="message" rows="4" class="outline w-full p-4 pt-10 mb-2 rounded"></textarea>
    <div class="flex justify-center">
        <input class="border-4 border-black hover:bg-black hover:text-white px-1 rounded-lg cursor-pointer" type="submit" value="Erstellen">
    </div>
    @error('message')
        <div class="text-red-400 text-center mt-2">
            {{ $message }}    
        </div>
    @enderror
</form>

resources/views/message/index.blade.php
@extends('template')

@section('content')
    @include('message.create')
    <hr class="border-gray-300 my-6" />
    <h1 class="text-center text-4xl mb-4 font-bold">Nachrichten</h1>
    @forelse ($messages as $item)
        <div class="relative border-4 border-black rounded-lg p-4 mb-8">
            {{ $item->message }} 
            <span class=" bg-white border-4 border-black absolute rounded-full z-1 px-2 -bottom-4 -right-4 text-sm">
                {{ $item->created_at->diffForHumans() }}
            </span>
            <form method="post" action="{{ route('message.destroy', [$item]) }}">
                @csrf
                @method('DELETE')
                <input type="submit" value="&times;" class=" bg-white border-4 border-black absolute rounded-full px-2 -top-4 z-1 -right-4 hover:bg-black hover:text-white cursor-pointer">
            </form>
        </div>
    @empty 
        <div class="text-center mb-4">
            Keine Nachrichten. 
        </div>
    @endforelse
    <div x-data="{ trashed: false }">
        <div class="flex justify-center">
            <button @click="trashed=!trashed" class="border-4 border-black hover:bg-black hover:text-white px-2 rounded-lg cursor-pointer">
                <span x-text="trashed? 'Verstecke gelöschte Nachrichten.': 'Zeige gelöschte Nachrichten.'"></span>
            </button>    
        </div>
        <div x-show="trashed">
            <hr class="border-gray-300 my-6" />
            <h1 class="text-center text-4xl mb-4 font-bold text-gray-400">Gelöschte Nachrichten</h1>
            @forelse ($trashed as $item)
            <div class="relative border-4 border-gray-300 text-gray-400 rounded-lg p-4 mb-8 pr-10">
                    {{ $item->message }}
                    <span class="z-1 bg-white border-4 border-gray-300 text-gray-400 absolute rounded-full px-2 -bottom-4 -right-4 text-sm">
                        {{ $item->deleted_at->diffForHumans() }}
                    </span>    
                    <form method="post" action="{{ route('message.restore', [$item->id]) }}">
                        @csrf
                        <input type="submit" value="&#x21bb;" class="z-1 bg-white border-4 text-gray-400 border-gray-300 absolute rounded-full px-2 -top-4 -right-4 hover:bg-gray-300 hover:text-white cursor-pointer">
                    </form>
                </div>
            @empty
            <div class="text-center mb-6 text-gray-400">
                Keine gelöschten Nachrichten. 
            </div>
            @endforelse
        </div>
    </div>
@endsection

resources/views/template.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @vite('resources/css/app.css')
    <script src="//unpkg.com/alpinejs" defer></script>
    <title>@yield('title', "Kummerkasten")</title>
</head>
<body>
    <div class="container mx-auto p-4">
        @yield('content')
    </div>
</body>
</html>